name: 'Deploy to Docker Hub'

on:
    push:
        branches:
            - 'master'

env:
    DOCKER_HUB_REPOSITORY: dev-container

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Grab the source code to current working directory
            - name: 'Clone source code'
              uses: actions/checkout@v2

            # Login to Docker Hub using credentials stored in repo secrets
            - name: 'Login to Docker Hub'
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            # Build the application image and tag with specified name
            - name: 'Build dev-container image'
              run: docker build -f .devcontainer/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:latest .

            # Push the built image to Docker Hub container registry
            - name: 'Push built image to Docker Hub'
              run: docker push ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:latest
